name: Isort
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  isort:
    runs-on: ubuntu-latest

    steps:
      - uses: aldjemy/aldjemy/.github/workflows/_bootstrap-poetry.yml@main
      - name: Isort
        run: poetry run isort --check .
