name: Isort
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  isort:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.9"

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: "1.1.11"
      - name: Setup cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: venv-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: |
          poetry install
      - name: Isort
        run: poetry run isort --check .
