name: Isort
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  isort:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.2.0
        with:
          poetry-version: "1.1.15"
      - name: Install dependencies
        run: poetry install
      - name: Isort
        run: poetry run isort --check .
